name: Sync Upyun

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mai/**' # 目录内容有变化执行工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Deploy
        uses: her-cat/upyun-deployer@v1
        with:
          bucket: ${{ secrets.UPYUN_BUCKET }}
          operator: ${{ secrets.OPERATOR }}
          password: ${{ secrets.OPERATOR_PASSWORD }}
          dir: mai # 需同步的本地目录
